# Generated by Django 2.1.4 on 2019-01-02 01:43

from django.db import migrations, models
import processing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('function', models.CharField(max_length=30)),
                ('number_of_images', models.PositiveSmallIntegerField(default=1)),
                ('number_of_parameters', models.PositiveSmallIntegerField(default=0)),
                ('params', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to=processing.models.user_directory_path)),
            ],
        ),
    ]
