# Generated by Django 2.1.4 on 2019-01-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingfunction',
            name='type',
            field=models.CharField(default='type', max_length=10),
            preserve_default=False,
        ),
    ]
