# Generated by Django 2.1.4 on 2018-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_processingfunction_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingfunction',
            name='number_of_images',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
