# Generated by Django 2.1.4 on 2018-12-13 15:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_auto_20181213_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingfunction',
            name='number_of_images',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='processingfunction',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
