# Generated by Django 2.1.4 on 2018-12-13 15:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_auto_20181213_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingfunction',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
